### ISSUE TITLE
Cannot find module 'aws-cdk-lib' or its corresponding type declarations.

### ISSUE THREAD

**Issue by itsbeautifullife** [w-okada/flect-chime-sdk-demo#10]
Node version : v12.22.6
NPM version : 6.14.15

$ npm run build_all

> backend@0.1.0 build_all /var/www/flect-chime-sdk-demo/backend
> npm run build && npm run build:lambda && cdk deploy --outputs-file cfn_outputs.json

> backend@0.1.0 build /var/www/flect-chime-sdk-demo/backend
> tsc

node_modules/@aws-cdk/assert/lib/expect.d.ts:1:22 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.

1 import * as cdk from 'aws-cdk-lib';
                       ~~~~~~~~~~~~~

node_modules/@aws-cdk/assert/lib/expect.d.ts:2:22 - error TS2307: Cannot find module 'aws-cdk-lib/cx-api' or its corresponding type declarations.

2 import * as api from 'aws-cdk-lib/cx-api';
                       ~~~~~~~~~~~~~~~~~~~~

**Comment by w-okada** [comment]
Currently I don't have the environment as same as yours (Node version : v12.22.6, NPM version : 6.14.15).
In my environment (node:  v14.18.1, npm: 8.1.2), I could not reproduce your issue.

Did you do this?
> $ npm install

And can you check whether aws-cdk-lib in node_modules folder?

**Comment by itsbeautifullife** [comment]
Thanks for looking into it . I checked in `node_modules` even after doing `npm i` multiple times it won't create `aws-cdk-lib` in node_moules 

So I upgraded npm and node to your provided ones and run `npm install aws-cdk-lib`. It started working

**Comment by w-okada** [comment]
Sounds good!
