### ISSUE TITLE
QUESTION - BGM from server

### ISSUE THREAD

**Issue by chuckntaylor** [w-okada/flect-chime-sdk-demo#2]
Hi, I saw your response to my questions on your [BGM/SE with Amazon Chime SDK article](https://dannadori.medium.com/bgm-se-with-amazon-chime-sdk-6d144aa84490). I had asked about whether or not it was possible to add background music to a Chime meeting from the server side, and you had mentioned:
_"Normaly We can not. But I have some workaround to do this. But some additional inspection is needed."_

I was wondering if you were willing to elaborate, or if a follow-up article related to this might be in the works?

Thank you for sharing your insights!

**Comment by w-okada** [comment]
YES. I will. But I have a lot of tasks in my list... Please wait.
But, I can not promise my idea can satisify your demand because the idea is just a workaround.

So, if you seriously need the solution, I should say with Amazon Chime SDK can not add BGM from server.

**Comment by chuckntaylor** [comment]
Thanks for taking the time to get back to me. I'm thinking of exploring
other means of playing the music - just a matter of synching it I suppose
(possibly with socket.io), but I will need to test if this gets messed up
due to everyone's microphones picking up the music from their speakers.
I'll keep my eye out for your other articles!

**Comment by w-okada** [comment]
I close this issue because this issue is very old and no bug. 
If you want to re-open, you can.
