### ISSUE TITLE
Cant change to back camera (Android)

### ISSUE THREAD

**Issue by dec4des** [w-okada/flect-chime-sdk-demo#3]
Hi everyone,
i have an issue, 
I'm running the demo but I can't select the back camera from dropdown menu ( Select Device ) on my android device, when I select Back Camera immediately changes to Front Camera, but in iOS works well. 

I tried with 3 android devices and error still happens,  Do you know what's happening? 

thanks and hope you have a great day.

**Comment by w-okada** [comment]
Please use frontend7
