### ISSUE TITLE
OneTimeCode SignInError

### ISSUE THREAD

**Issue by ruzanowski** [w-okada/flect-chime-sdk-demo#6]
Hello,

I try to use OneTimeCode, however, whenever I click, it is always an error like below:
![image](https://user-images.githubusercontent.com/18686966/123950464-006dec80-d9a4-11eb-97df-7a0893da9b90.png)

Have you encountered such an issue?

Best regards,
Sebastian

**Comment by w-okada** [comment]
Ah,,, this function is experimental.
But if you want to use, please select code which described under QRCode.
This code is onetime, so if you select wrong code, the code will become not valid.
If you select wrong code, please regenerate new onetime code.
