### ISSUE TITLE
ソースコード修正方法に関するお問い合わせ

### ISSUE THREAD

**Issue by noyeah-man** [w-okada/flect-chime-sdk-demo#8]
environment: windows10

おはようございます
本当にいいソースを提供してくださってありがとうございます。
私は開発初心者です。
先輩のソースコードを 修正して使いたいんですが
frontendコードを修正してbuild以降にsync.shを実行してもfrontendは変わりません。

reactソースを修正したいですが、どうすれば良いのか知りたいです。

不足な日本語の実力、すみません。

**Comment by noyeah-man** [comment]
aws cloudfront console -> distributions -> select ID -> TAB Invalidation -> create Invalidation -> index.html -> create Invalidation

上記のように設定して解決しました。 ありがとうございます。

**Comment by w-okada** [comment]
ご連絡ありがごうとうございます。十分わかりやすい日本語です。
そうですね。cloudfrontを使う場合はinvalidateする必要があります。
もし面倒なら、backend/bin/config.tsで
export const USE_CDN = false  
とするとcloudfrontを使わなくなります。
