### ISSUE TITLE
room create できない問題

### ISSUE THREAD

**Issue by noyeah-man** [w-okada/flect-chime-sdk-demo#9]
おはようございます

よく質問してすみません。

先輩がアップしたバージョンで実行すると、写真のようなエラーが発生します。

部屋が作られない理由が知りたいです

助けてもらえますか

![1](https://user-images.githubusercontent.com/83991978/127075081-16a11a52-8b89-406b-8a7c-21348347f048.PNG)

![2](https://user-images.githubusercontent.com/83991978/127075100-09e0cec9-9601-43e9-a747-046e5fa8d5b5.PNG)

ありがとうございました！

**Comment by w-okada** [comment]
backend/bin/config.tsを見せてください。

**Comment by noyeah-man** [comment]
> backend / bin / config.ts을 보여주세요.

export const BACKEND_STACK_NAME = 'flect-chime-demo'
export const FRONTEND_LOCAL_DEV = true
export const USE_DOCKER = false
export const USE_CDN = true

위와 같이 설정했습니다.

**Comment by noyeah-man** [comment]
> > backend / bin / config.ts을 보여주세요.
> 
> export const BACKEND_STACK_NAME = 'flect-chime-demo'
> export const FRONTEND_LOCAL_DEV = true
> export const USE_DOCKER = false
> export const USE_CDN = true
> 
> 위와 같이 설정했습니다.
すいません

LOCAL_DEVをtrueに変えたら解決されました

詳しく確認したいと思います。

支援ありがとうございます。

ㅠㅠ
